### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by thelilpufferfish** [thelilpufferfish/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structure on a webpage
so that i can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN i see four boxes title HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Nishant9771** [comment]
There are some Listed Websites where you can check once :

freecodecamp
MDN WEB
codecademy
coursera
w3school
or last you can explore any repositories regading that on github.
